title: Cornetto Database at the HEM
wg_title: 
email: info@rism.digital
description: "Cornetto Database at the HEM"
baseurl: "/cornetto-database" # example /cornetto-database
url: "https://lpugin.github.io"
twitter_username: RISM_Music
twitter:
  card: summary

enable_search: false

defaults:
  - scope:
      path: ""
    values:
      image: /images/logo-square.png

follow_us:
  facebook: https://www.facebook.com/hemgeneve
  youtube: https://www.youtube.com/channel/UCKWlqRwsdH-5J61BsRUm4Tw

sponsors:
  - url: https://www.hesge.ch/hem/
    logo: hem.jpg

languages: ["en"]
default_lang: "en"
exclude_from_localization: ["assets", "javascript", "images", "css", "README.md"]
parallel_localization: false
lang_from_path: false
sass:
  sourcemap: never

theme: rism-theme

remote_csv:
  cornetto:
    source: https://docs.google.com/spreadsheets/d/1XrARBpah9CL_BMj3XRsyw1CL5o8RVheDyuAg5ya0z4I/export?exportFormat=csv

src_link: https://github.com/lpugin/cornetto-database/tree/main

